print('Hellow!')
a = int(input('Введите число: \n'))
b = int(input('Введите число: \n'))
c = int(input('Введите число: \n'))
print(a)
print(b)
print(c)
print(a + b + c)
print('Hellow!')
print('Hellow!')
